build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.4
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy"
  - activate test-environment
  - conda install -c scitools shapely
  - conda install -c ioos rtree
  - pip install nose2 networkx svg.path sympy msgpack-python
  - pip install .

  - appveyor DownloadFile http://mirror.cs.umn.edu/blender.org/release/Blender2.78/blender-2.78a-windows64.zip
  - 7z x blender-2.78a-windows64.zip -o C:\blender -y
  - PATH %PATH%;C:\blender


test_script:
  - nose2