language: python
sudo: required
dist: trusty

python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'

before_deploy:
- sudo apt-get install pandoc -y
- sudo pip install pypandoc

deploy:
  provider: pypi
  user: mikedh
  password:
    secure: HbsOtokNjlpRE98DpeeX1uPzMR3XWZbovtyPA2gS4eobkod7YyBXDgj30uOwcMvJMo4sX7Fi3X59qY43qHLiftTFhaMtN4+E1N0HaVVfmTi/Iv/L4qd4gMjCjg6M7N1wiCmYA+ceB8pAGOzLoo2K2uXixBfkeQjxUZjKTHfQYlM

before_install:
- sudo apt-get update
- sudo apt-get install -y libgeos-dev libspatialindex-dev openscad blender
- if [[ "${TRAVIS_PYTHON_VERSION}" == 2.7 ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi;
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=/home/travis/miniconda2/bin:/home/travis/miniconda3/bin:$PATH
- conda update --yes conda
- conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
- pip install nose2

install: pip install .[all]

script: 
- cd tests
- nose2
- cd ../examples
- for f in *.py; do python "$f" -nw; done
- cd ..