language: python
sudo: required
dist: trusty

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-scipy python-numpy libgeos-dev libspatialindex*
  - virtualenv --system-site-packages ../trimesh_testing
  - source ../trimesh_testing/bin/activate
  - pip install nose

install: pip install -e .[path]
before_script: cd tests
script: "python path_tests.py; python trimesh_tests.py"
