language: python
sudo: required
dist: trusty

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgeos-dev libspatialindex*
  
install: pip install -e .[path]
before_script: cd tests
script: nosetests
