language: python
sudo: required
dist: trusty

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgeos-dev libspatialindex*
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - sudo conda install scipy
  
install: pip install -e .[path]
before_script: cd tests
script: nosetests
