language: python
sudo: required
dist: trusty

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-scipy python-numpy libgeos-dev libspatialindex*
  - pip install nose

install: pip install -e .[path]
before_script: cd tests
script: nosetests
