language: python
sudo: required
dist: trusty

python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'

before_deploy:
- sudo apt-get install pandoc -y
- sudo pip install pypandoc

deploy:
  provider: pypi
  user: mikedh
  password:
    secure: HbsOtokNjlpRE98DpeeX1uPzMR3XWZbovtyPA2gS4eobkod7YyBXDgj30uOwcMvJMo4sX7Fi3X59qY43qHLiftTFhaMtN4+E1N0HaVVfmTi/Iv/L4qd4gMjCjg6M7N1wiCmYA+ceB8pAGOzLoo2K2uXixBfkeQjxUZjKTHfQYlM

before_install:
- sudo apt-get update
- sudo apt-get install -y python-scipy python-numpy libgeos-dev libspatialindex-dev openscad blender
- virtualenv --system-site-packages ../trimesh_test
- source ../trimesh_test/bin/activate
- pip install nose2
install: pip install .[all]

script: 
- if [[ "${TRAVIS_PYTHON_VERSION}" == 2.7 ]]; then export TESTCMD=nose2; else export TESTCMD="nose2-${TRAVIS_PYTHON_VERSION}"; fi;
- echo $TESTCMD
- $TESTCMD
- cd examples
- for f in *.py; do python "$f" -nw; done
- cd ..